apiVersion: v1
kind: PersistentVolume
metadata:
  name: auth-pv
  labels:
    type: local
spec:
  storageClassName: 'manual'
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/d/work/2021/mastercard/test/mnt/mongo-data'
